/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = iambackoffice.Client.OpenAPIDateConverter;

namespace iambackoffice.Model
{
    /// <summary>
    /// IambackofficeUserTwoFactorConfiguration
    /// </summary>
    [DataContract(Name = "iambackofficeUserTwoFactorConfiguration")]
    public partial class IambackofficeUserTwoFactorConfiguration : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IambackofficeUserTwoFactorConfiguration" /> class.
        /// </summary>
        /// <param name="methods">methods.</param>
        /// <param name="recoveryCodes">recoveryCodes.</param>
        public IambackofficeUserTwoFactorConfiguration(List<IambackofficeTwoFactorMethod> methods = default(List<IambackofficeTwoFactorMethod>), List<string> recoveryCodes = default(List<string>))
        {
            this.Methods = methods;
            this.RecoveryCodes = recoveryCodes;
            this.AdditionalProperties = new Dictionary<string, object>();
        }

        /// <summary>
        /// Gets or Sets Methods
        /// </summary>
        [DataMember(Name = "methods", EmitDefaultValue = false)]
        public List<IambackofficeTwoFactorMethod> Methods { get; set; }

        /// <summary>
        /// Gets or Sets RecoveryCodes
        /// </summary>
        [DataMember(Name = "recoveryCodes", EmitDefaultValue = false)]
        public List<string> RecoveryCodes { get; set; }

        /// <summary>
        /// Gets or Sets additional properties
        /// </summary>
        [JsonExtensionData]
        public IDictionary<string, object> AdditionalProperties { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IambackofficeUserTwoFactorConfiguration {\n");
            sb.Append("  Methods: ").Append(Methods).Append("\n");
            sb.Append("  RecoveryCodes: ").Append(RecoveryCodes).Append("\n");
            sb.Append("  AdditionalProperties: ").Append(AdditionalProperties).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
