/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = iambackoffice.Client.OpenAPIDateConverter;

namespace iambackoffice.Model
{
    /// <summary>
    /// IambackofficeAuthenticatorConfiguration
    /// </summary>
    [DataContract(Name = "iambackofficeAuthenticatorConfiguration")]
    public partial class IambackofficeAuthenticatorConfiguration : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IambackofficeAuthenticatorConfiguration" /> class.
        /// </summary>
        /// <param name="algorithm">algorithm.</param>
        /// <param name="codeLength">codeLength.</param>
        /// <param name="timeStep">timeStep.</param>
        public IambackofficeAuthenticatorConfiguration(string algorithm = default(string), int codeLength = default(int), int timeStep = default(int))
        {
            this.Algorithm = algorithm;
            this.CodeLength = codeLength;
            this.TimeStep = timeStep;
        }

        /// <summary>
        /// Gets or Sets Algorithm
        /// </summary>
        [DataMember(Name = "algorithm", EmitDefaultValue = false)]
        public string Algorithm { get; set; }

        /// <summary>
        /// Gets or Sets CodeLength
        /// </summary>
        [DataMember(Name = "codeLength", EmitDefaultValue = false)]
        public int CodeLength { get; set; }

        /// <summary>
        /// Gets or Sets TimeStep
        /// </summary>
        [DataMember(Name = "timeStep", EmitDefaultValue = false)]
        public int TimeStep { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IambackofficeAuthenticatorConfiguration {\n");
            sb.Append("  Algorithm: ").Append(Algorithm).Append("\n");
            sb.Append("  CodeLength: ").Append(CodeLength).Append("\n");
            sb.Append("  TimeStep: ").Append(TimeStep).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
