/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeCreateGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeCreateGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeCreateGroupRequest
        //private IambackofficeCreateGroupRequest instance;

        public IambackofficeCreateGroupRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeCreateGroupRequest
            //instance = new IambackofficeCreateGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeCreateGroupRequest
        /// </summary>
        [Fact]
        public void IambackofficeCreateGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeCreateGroupRequest
            //Assert.IsType<IambackofficeCreateGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
