/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeRegistrationRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeRegistrationRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeRegistrationRequest
        //private IambackofficeRegistrationRequest instance;

        public IambackofficeRegistrationRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeRegistrationRequest
            //instance = new IambackofficeRegistrationRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeRegistrationRequest
        /// </summary>
        [Fact]
        public void IambackofficeRegistrationRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeRegistrationRequest
            //Assert.IsType<IambackofficeRegistrationRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Registration'
        /// </summary>
        [Fact]
        public void RegistrationTest()
        {
            // TODO unit test for the property 'Registration'
        }

        /// <summary>
        /// Test the property 'SendSetPasswordEmail'
        /// </summary>
        [Fact]
        public void SendSetPasswordEmailTest()
        {
            // TODO unit test for the property 'SendSetPasswordEmail'
        }

        /// <summary>
        /// Test the property 'SkipRegistrationVerification'
        /// </summary>
        [Fact]
        public void SkipRegistrationVerificationTest()
        {
            // TODO unit test for the property 'SkipRegistrationVerification'
        }

        /// <summary>
        /// Test the property 'SkipVerification'
        /// </summary>
        [Fact]
        public void SkipVerificationTest()
        {
            // TODO unit test for the property 'SkipVerification'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
    }
}
