/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeUser
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeUserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeUser
        //private IambackofficeUser instance;

        public IambackofficeUserTests()
        {
            // TODO uncomment below to create an instance of IambackofficeUser
            //instance = new IambackofficeUser();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeUser
        /// </summary>
        [Fact]
        public void IambackofficeUserInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeUser
            //Assert.IsType<IambackofficeUser>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'BirthDate'
        /// </summary>
        [Fact]
        public void BirthDateTest()
        {
            // TODO unit test for the property 'BirthDate'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FirstName'
        /// </summary>
        [Fact]
        public void FirstNameTest()
        {
            // TODO unit test for the property 'FirstName'
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'ImageUrl'
        /// </summary>
        [Fact]
        public void ImageUrlTest()
        {
            // TODO unit test for the property 'ImageUrl'
        }

        /// <summary>
        /// Test the property 'InsertInstant'
        /// </summary>
        [Fact]
        public void InsertInstantTest()
        {
            // TODO unit test for the property 'InsertInstant'
        }

        /// <summary>
        /// Test the property 'LastLoginInstant'
        /// </summary>
        [Fact]
        public void LastLoginInstantTest()
        {
            // TODO unit test for the property 'LastLoginInstant'
        }

        /// <summary>
        /// Test the property 'LastName'
        /// </summary>
        [Fact]
        public void LastNameTest()
        {
            // TODO unit test for the property 'LastName'
        }

        /// <summary>
        /// Test the property 'LastUpdateInstant'
        /// </summary>
        [Fact]
        public void LastUpdateInstantTest()
        {
            // TODO unit test for the property 'LastUpdateInstant'
        }

        /// <summary>
        /// Test the property 'MiddleName'
        /// </summary>
        [Fact]
        public void MiddleNameTest()
        {
            // TODO unit test for the property 'MiddleName'
        }

        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'PasswordChangeRequired'
        /// </summary>
        [Fact]
        public void PasswordChangeRequiredTest()
        {
            // TODO unit test for the property 'PasswordChangeRequired'
        }

        /// <summary>
        /// Test the property 'PasswordLastUpdateInstant'
        /// </summary>
        [Fact]
        public void PasswordLastUpdateInstantTest()
        {
            // TODO unit test for the property 'PasswordLastUpdateInstant'
        }

        /// <summary>
        /// Test the property 'PreferredLanguages'
        /// </summary>
        [Fact]
        public void PreferredLanguagesTest()
        {
            // TODO unit test for the property 'PreferredLanguages'
        }

        /// <summary>
        /// Test the property 'Registrations'
        /// </summary>
        [Fact]
        public void RegistrationsTest()
        {
            // TODO unit test for the property 'Registrations'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }

        /// <summary>
        /// Test the property 'TwoFactor'
        /// </summary>
        [Fact]
        public void TwoFactorTest()
        {
            // TODO unit test for the property 'TwoFactor'
        }

        /// <summary>
        /// Test the property 'Username'
        /// </summary>
        [Fact]
        public void UsernameTest()
        {
            // TODO unit test for the property 'Username'
        }

        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Fact]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }
    }
}
