/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeAssignRolesRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeAssignRolesRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeAssignRolesRequest
        //private IambackofficeAssignRolesRequest instance;

        public IambackofficeAssignRolesRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeAssignRolesRequest
            //instance = new IambackofficeAssignRolesRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeAssignRolesRequest
        /// </summary>
        [Fact]
        public void IambackofficeAssignRolesRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeAssignRolesRequest
            //Assert.IsType<IambackofficeAssignRolesRequest>(instance);
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'RoleCodes'
        /// </summary>
        [Fact]
        public void RoleCodesTest()
        {
            // TODO unit test for the property 'RoleCodes'
        }
    }
}
