/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeLoginResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeLoginResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeLoginResponse
        //private IambackofficeLoginResponse instance;

        public IambackofficeLoginResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeLoginResponse
            //instance = new IambackofficeLoginResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeLoginResponse
        /// </summary>
        [Fact]
        public void IambackofficeLoginResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeLoginResponse
            //Assert.IsType<IambackofficeLoginResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }

        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }

        /// <summary>
        /// Test the property 'TwoFactorId'
        /// </summary>
        [Fact]
        public void TwoFactorIdTest()
        {
            // TODO unit test for the property 'TwoFactorId'
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }
    }
}
