/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeDevice
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeDeviceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeDevice
        //private IambackofficeDevice instance;

        public IambackofficeDeviceTests()
        {
            // TODO uncomment below to create an instance of IambackofficeDevice
            //instance = new IambackofficeDevice();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeDevice
        /// </summary>
        [Fact]
        public void IambackofficeDeviceInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeDevice
            //Assert.IsType<IambackofficeDevice>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'DeviceType'
        /// </summary>
        [Fact]
        public void DeviceTypeTest()
        {
            // TODO unit test for the property 'DeviceType'
        }
    }
}
