/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeUserRegistration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeUserRegistrationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeUserRegistration
        //private IambackofficeUserRegistration instance;

        public IambackofficeUserRegistrationTests()
        {
            // TODO uncomment below to create an instance of IambackofficeUserRegistration
            //instance = new IambackofficeUserRegistration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeUserRegistration
        /// </summary>
        [Fact]
        public void IambackofficeUserRegistrationInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeUserRegistration
            //Assert.IsType<IambackofficeUserRegistration>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'PreferredLanguages'
        /// </summary>
        [Fact]
        public void PreferredLanguagesTest()
        {
            // TODO unit test for the property 'PreferredLanguages'
        }

        /// <summary>
        /// Test the property 'Roles'
        /// </summary>
        [Fact]
        public void RolesTest()
        {
            // TODO unit test for the property 'Roles'
        }

        /// <summary>
        /// Test the property 'Timezone'
        /// </summary>
        [Fact]
        public void TimezoneTest()
        {
            // TODO unit test for the property 'Timezone'
        }
    }
}
