/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeRegistrationResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeRegistrationResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeRegistrationResponse
        //private IambackofficeRegistrationResponse instance;

        public IambackofficeRegistrationResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeRegistrationResponse
            //instance = new IambackofficeRegistrationResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeRegistrationResponse
        /// </summary>
        [Fact]
        public void IambackofficeRegistrationResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeRegistrationResponse
            //Assert.IsType<IambackofficeRegistrationResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }

        /// <summary>
        /// Test the property 'Registration'
        /// </summary>
        [Fact]
        public void RegistrationTest()
        {
            // TODO unit test for the property 'Registration'
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
