/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeSearchGroupsRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeSearchGroupsRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeSearchGroupsRequest
        //private IambackofficeSearchGroupsRequest instance;

        public IambackofficeSearchGroupsRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeSearchGroupsRequest
            //instance = new IambackofficeSearchGroupsRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeSearchGroupsRequest
        /// </summary>
        [Fact]
        public void IambackofficeSearchGroupsRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeSearchGroupsRequest
            //Assert.IsType<IambackofficeSearchGroupsRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Filters'
        /// </summary>
        [Fact]
        public void FiltersTest()
        {
            // TODO unit test for the property 'Filters'
        }

        /// <summary>
        /// Test the property 'FiltersMask'
        /// </summary>
        [Fact]
        public void FiltersMaskTest()
        {
            // TODO unit test for the property 'FiltersMask'
        }
    }
}
