/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeLoginRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeLoginRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeLoginRequest
        //private IambackofficeLoginRequest instance;

        public IambackofficeLoginRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeLoginRequest
            //instance = new IambackofficeLoginRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeLoginRequest
        /// </summary>
        [Fact]
        public void IambackofficeLoginRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeLoginRequest
            //Assert.IsType<IambackofficeLoginRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'IpAddress'
        /// </summary>
        [Fact]
        public void IpAddressTest()
        {
            // TODO unit test for the property 'IpAddress'
        }

        /// <summary>
        /// Test the property 'LoginId'
        /// </summary>
        [Fact]
        public void LoginIdTest()
        {
            // TODO unit test for the property 'LoginId'
        }

        /// <summary>
        /// Test the property 'MetaData'
        /// </summary>
        [Fact]
        public void MetaDataTest()
        {
            // TODO unit test for the property 'MetaData'
        }

        /// <summary>
        /// Test the property 'NoTokens'
        /// </summary>
        [Fact]
        public void NoTokensTest()
        {
            // TODO unit test for the property 'NoTokens'
        }

        /// <summary>
        /// Test the property 'Password'
        /// </summary>
        [Fact]
        public void PasswordTest()
        {
            // TODO unit test for the property 'Password'
        }

        /// <summary>
        /// Test the property 'TwoFactorTrustId'
        /// </summary>
        [Fact]
        public void TwoFactorTrustIdTest()
        {
            // TODO unit test for the property 'TwoFactorTrustId'
        }
    }
}
