/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeCreateGroupResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeCreateGroupResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeCreateGroupResponse
        //private IambackofficeCreateGroupResponse instance;

        public IambackofficeCreateGroupResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeCreateGroupResponse
            //instance = new IambackofficeCreateGroupResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeCreateGroupResponse
        /// </summary>
        [Fact]
        public void IambackofficeCreateGroupResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeCreateGroupResponse
            //Assert.IsType<IambackofficeCreateGroupResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Group'
        /// </summary>
        [Fact]
        public void GroupTest()
        {
            // TODO unit test for the property 'Group'
        }
    }
}
