/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeGetUserResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeGetUserResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeGetUserResponse
        //private IambackofficeGetUserResponse instance;

        public IambackofficeGetUserResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeGetUserResponse
            //instance = new IambackofficeGetUserResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeGetUserResponse
        /// </summary>
        [Fact]
        public void IambackofficeGetUserResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeGetUserResponse
            //Assert.IsType<IambackofficeGetUserResponse>(instance);
        }

        /// <summary>
        /// Test the property 'User'
        /// </summary>
        [Fact]
        public void UserTest()
        {
            // TODO unit test for the property 'User'
        }
    }
}
