/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeAssignRolesResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeAssignRolesResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeAssignRolesResponse
        //private IambackofficeAssignRolesResponse instance;

        public IambackofficeAssignRolesResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeAssignRolesResponse
            //instance = new IambackofficeAssignRolesResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeAssignRolesResponse
        /// </summary>
        [Fact]
        public void IambackofficeAssignRolesResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeAssignRolesResponse
            //Assert.IsType<IambackofficeAssignRolesResponse>(instance);
        }

        /// <summary>
        /// Test the property 'RoleCodes'
        /// </summary>
        [Fact]
        public void RoleCodesTest()
        {
            // TODO unit test for the property 'RoleCodes'
        }
    }
}
