/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeLoginMfaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeLoginMfaRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeLoginMfaRequest
        //private IambackofficeLoginMfaRequest instance;

        public IambackofficeLoginMfaRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeLoginMfaRequest
            //instance = new IambackofficeLoginMfaRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeLoginMfaRequest
        /// </summary>
        [Fact]
        public void IambackofficeLoginMfaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeLoginMfaRequest
            //Assert.IsType<IambackofficeLoginMfaRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'TwoFactorId'
        /// </summary>
        [Fact]
        public void TwoFactorIdTest()
        {
            // TODO unit test for the property 'TwoFactorId'
        }
    }
}
