/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeUserTwoFactorConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeUserTwoFactorConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeUserTwoFactorConfiguration
        //private IambackofficeUserTwoFactorConfiguration instance;

        public IambackofficeUserTwoFactorConfigurationTests()
        {
            // TODO uncomment below to create an instance of IambackofficeUserTwoFactorConfiguration
            //instance = new IambackofficeUserTwoFactorConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeUserTwoFactorConfiguration
        /// </summary>
        [Fact]
        public void IambackofficeUserTwoFactorConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeUserTwoFactorConfiguration
            //Assert.IsType<IambackofficeUserTwoFactorConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'Methods'
        /// </summary>
        [Fact]
        public void MethodsTest()
        {
            // TODO unit test for the property 'Methods'
        }

        /// <summary>
        /// Test the property 'RecoveryCodes'
        /// </summary>
        [Fact]
        public void RecoveryCodesTest()
        {
            // TODO unit test for the property 'RecoveryCodes'
        }
    }
}
