/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeDisableUserMfaRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeDisableUserMfaRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeDisableUserMfaRequest
        //private IambackofficeDisableUserMfaRequest instance;

        public IambackofficeDisableUserMfaRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeDisableUserMfaRequest
            //instance = new IambackofficeDisableUserMfaRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeDisableUserMfaRequest
        /// </summary>
        [Fact]
        public void IambackofficeDisableUserMfaRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeDisableUserMfaRequest
            //Assert.IsType<IambackofficeDisableUserMfaRequest>(instance);
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'Code'
        /// </summary>
        [Fact]
        public void CodeTest()
        {
            // TODO unit test for the property 'Code'
        }

        /// <summary>
        /// Test the property 'MethodId'
        /// </summary>
        [Fact]
        public void MethodIdTest()
        {
            // TODO unit test for the property 'MethodId'
        }
    }
}
