/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeTwoFactorMethod
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeTwoFactorMethodTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeTwoFactorMethod
        //private IambackofficeTwoFactorMethod instance;

        public IambackofficeTwoFactorMethodTests()
        {
            // TODO uncomment below to create an instance of IambackofficeTwoFactorMethod
            //instance = new IambackofficeTwoFactorMethod();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeTwoFactorMethod
        /// </summary>
        [Fact]
        public void IambackofficeTwoFactorMethodInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeTwoFactorMethod
            //Assert.IsType<IambackofficeTwoFactorMethod>(instance);
        }

        /// <summary>
        /// Test the property 'Authenticator'
        /// </summary>
        [Fact]
        public void AuthenticatorTest()
        {
            // TODO unit test for the property 'Authenticator'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Method'
        /// </summary>
        [Fact]
        public void MethodTest()
        {
            // TODO unit test for the property 'Method'
        }

        /// <summary>
        /// Test the property 'MobilePhone'
        /// </summary>
        [Fact]
        public void MobilePhoneTest()
        {
            // TODO unit test for the property 'MobilePhone'
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
    }
}
