/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeGenerateSecretForQRResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeGenerateSecretForQRResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeGenerateSecretForQRResponse
        //private IambackofficeGenerateSecretForQRResponse instance;

        public IambackofficeGenerateSecretForQRResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeGenerateSecretForQRResponse
            //instance = new IambackofficeGenerateSecretForQRResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeGenerateSecretForQRResponse
        /// </summary>
        [Fact]
        public void IambackofficeGenerateSecretForQRResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeGenerateSecretForQRResponse
            //Assert.IsType<IambackofficeGenerateSecretForQRResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Secret'
        /// </summary>
        [Fact]
        public void SecretTest()
        {
            // TODO unit test for the property 'Secret'
        }
    }
}
