/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeAuthenticatorConfiguration
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeAuthenticatorConfigurationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeAuthenticatorConfiguration
        //private IambackofficeAuthenticatorConfiguration instance;

        public IambackofficeAuthenticatorConfigurationTests()
        {
            // TODO uncomment below to create an instance of IambackofficeAuthenticatorConfiguration
            //instance = new IambackofficeAuthenticatorConfiguration();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeAuthenticatorConfiguration
        /// </summary>
        [Fact]
        public void IambackofficeAuthenticatorConfigurationInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeAuthenticatorConfiguration
            //Assert.IsType<IambackofficeAuthenticatorConfiguration>(instance);
        }

        /// <summary>
        /// Test the property 'Algorithm'
        /// </summary>
        [Fact]
        public void AlgorithmTest()
        {
            // TODO unit test for the property 'Algorithm'
        }

        /// <summary>
        /// Test the property 'CodeLength'
        /// </summary>
        [Fact]
        public void CodeLengthTest()
        {
            // TODO unit test for the property 'CodeLength'
        }

        /// <summary>
        /// Test the property 'TimeStep'
        /// </summary>
        [Fact]
        public void TimeStepTest()
        {
            // TODO unit test for the property 'TimeStep'
        }
    }
}
