/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeLogoutRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeLogoutRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeLogoutRequest
        //private IambackofficeLogoutRequest instance;

        public IambackofficeLogoutRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeLogoutRequest
            //instance = new IambackofficeLogoutRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeLogoutRequest
        /// </summary>
        [Fact]
        public void IambackofficeLogoutRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeLogoutRequest
            //Assert.IsType<IambackofficeLogoutRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Global'
        /// </summary>
        [Fact]
        public void GlobalTest()
        {
            // TODO unit test for the property 'Global'
        }

        /// <summary>
        /// Test the property 'Tokens'
        /// </summary>
        [Fact]
        public void TokensTest()
        {
            // TODO unit test for the property 'Tokens'
        }
    }
}
