/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeSearchGroupsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeSearchGroupsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeSearchGroupsResponse
        //private IambackofficeSearchGroupsResponse instance;

        public IambackofficeSearchGroupsResponseTests()
        {
            // TODO uncomment below to create an instance of IambackofficeSearchGroupsResponse
            //instance = new IambackofficeSearchGroupsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeSearchGroupsResponse
        /// </summary>
        [Fact]
        public void IambackofficeSearchGroupsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeSearchGroupsResponse
            //Assert.IsType<IambackofficeSearchGroupsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Groups'
        /// </summary>
        [Fact]
        public void GroupsTest()
        {
            // TODO unit test for the property 'Groups'
        }
    }
}
