/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeAssignUserToGroupRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeAssignUserToGroupRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeAssignUserToGroupRequest
        //private IambackofficeAssignUserToGroupRequest instance;

        public IambackofficeAssignUserToGroupRequestTests()
        {
            // TODO uncomment below to create an instance of IambackofficeAssignUserToGroupRequest
            //instance = new IambackofficeAssignUserToGroupRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeAssignUserToGroupRequest
        /// </summary>
        [Fact]
        public void IambackofficeAssignUserToGroupRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeAssignUserToGroupRequest
            //Assert.IsType<IambackofficeAssignUserToGroupRequest>(instance);
        }

        /// <summary>
        /// Test the property 'TenantId'
        /// </summary>
        [Fact]
        public void TenantIdTest()
        {
            // TODO unit test for the property 'TenantId'
        }

        /// <summary>
        /// Test the property 'UserId'
        /// </summary>
        [Fact]
        public void UserIdTest()
        {
            // TODO unit test for the property 'UserId'
        }

        /// <summary>
        /// Test the property 'GroupId'
        /// </summary>
        [Fact]
        public void GroupIdTest()
        {
            // TODO unit test for the property 'GroupId'
        }
    }
}
