/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing IambackofficeMetaData
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IambackofficeMetaDataTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IambackofficeMetaData
        //private IambackofficeMetaData instance;

        public IambackofficeMetaDataTests()
        {
            // TODO uncomment below to create an instance of IambackofficeMetaData
            //instance = new IambackofficeMetaData();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IambackofficeMetaData
        /// </summary>
        [Fact]
        public void IambackofficeMetaDataInstanceTest()
        {
            // TODO uncomment below to test "IsType" IambackofficeMetaData
            //Assert.IsType<IambackofficeMetaData>(instance);
        }

        /// <summary>
        /// Test the property 'Device'
        /// </summary>
        [Fact]
        public void DeviceTest()
        {
            // TODO unit test for the property 'Device'
        }
    }
}
