/*
 * IamBackoffice Service
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * Contact: info@gemini-commerce.com
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using iambackoffice.Model;
using iambackoffice.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace iambackoffice.Test.Model
{
    /// <summary>
    ///  Class for testing SearchGroupsRequestFilters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SearchGroupsRequestFiltersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SearchGroupsRequestFilters
        //private SearchGroupsRequestFilters instance;

        public SearchGroupsRequestFiltersTests()
        {
            // TODO uncomment below to create an instance of SearchGroupsRequestFilters
            //instance = new SearchGroupsRequestFilters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SearchGroupsRequestFilters
        /// </summary>
        [Fact]
        public void SearchGroupsRequestFiltersInstanceTest()
        {
            // TODO uncomment below to test "IsType" SearchGroupsRequestFilters
            //Assert.IsType<SearchGroupsRequestFilters>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
    }
}
